name = "Fartherlands"
author = "Fartherlands"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8981d415fe247926f2982f62e0ced9a06ec0fe0cab23dd83692726be64ed603"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
