name = "Fartherlands"
author = "Fartherlands"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9fdba16afa68f90bcfcc1a8f01a417ccbae6260ef2e7089fd4d8d32aa0150ff"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
