name = "Fartherlands"
author = "Fartherlands"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0046d84a651960241759b0c8b4b864dddc1a32f2a3492addd59b2d65d06a9a56"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
